### ISSUE TITLE
Create ChatGPT and YouTube Connection and Prompt

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#10]
## Value Proposition

As a user, I would like to receive a personalized training plan based on the questions in the questionnaire, which is created by an AI.

## Description

!! - In this Section gives no image - !!

I also used the ChatGPT feature to generate custom workout plans. I ask the model questions about specific goals such as muscle building, endurance, or for beginners. ChatGPT's answers are based on retrieved exercise data and provide personalized workout plans that meet my users' individual needs and goals.

After generate the plan i connect the youtube API and search a exercise video for exercise and integrate it.

By combining these two features, I can provide my users with a comprehensive and customized training solution. This allows them to create effective and varied workout plans and efficiently achieve their fitness goals.

## Acceptance Criteria
- [ ] Chat-GPT connection
- [ ] youtube api connection
- [ ] getExercises() function
- [ ] generateTrainingPlan() component
- [ ] save data to localstorage
- [ ] display data in dashboard / exercise page

## Tasks

- [ ] create a featured branch
- [ ] I register with RapidAPI to get access to the ExerciseDB API.
- [ ] I search over youtube api a exercise video from exercise name
- [ ] I install the required packages, for the ExerciseDB API and @openai/api for ChatGPT.
- [ ] I create a function called getExercises() to retrieve the exercise data from the ExerciseDB API.
- [ ] I implement a function called generateTrainingPlan() to send ChatGPT requests to the OpenAI API and get responses.
- [ ] I create a Next.js component and integrate the ExerciseDB API and ChatGPT functions into it.
- [ ] I retrieve the exercise data from the ExerciseDB API and store it in local state.
- [ ] I use the existing question catalog, which contains different questions for exercise planning, such as muscle building, endurance, or beginner.
- [ ] I go through the question catalog and call the generateTrainingPlan() function.
- [ ] I get the selection of exercises from ChatGPT based on the questions in the question catalog.
- [ ] I format the training plan data and save it.
- [ ] The generated training plan is displayed on the dashboard page and the user can call the exercises in it.

**Comment by Kheirah** [comment]
Detailed. Precise. I love it 😍
