### ISSUE TITLE
Connect MongoDB Database

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#11]
## Value Proposition

As a user I would like to use a database to store my data and access it from different devices

## Description

!! - In this Section gives no image - !!

Storage of data and exchange between devices and the database.

## Acceptance Criteria
- [ ] general database for save data
- [ ] collection for profile data
- [ ] collection for trainingsdata
- [ ] connect db with next.js project

## Tasks

- [ ] create a featured branch
- [ ] create database in MongoDB
- [ ] create a collection "profile_data"
- [ ] create a collection "trainingsdata"
- [ ] connect db with next.js project
- [ ] use swr and mongosse for connecting
- [ ] create a swr config for configuration
