### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#12]
## Value Proposition

As a user I would like to see my data visually displayed in a chart

## Description
![screenshot-www figma com-2023 08 01-21_42_16](https://github.com/oliverhees/capstone/assets/38748506/38d2cf1d-1d97-4062-aa79-1427a13a2332)

## Acceptance Criteria
- [ ] visual chart for kg

## Tasks

- [ ] create a featured branch
- [ ] install dependencies
- [ ] insert chart on dashboard

**Comment by Kheirah** [comment]
I love charts! Don't forget to explicitly articulate the value proposition, though.

For example,
_As a user I would like to see my data visually displayed in a chart **so that I can track my progress.**_
