### ISSUE TITLE
Create the Profile Page

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#2]
## Value Proposition

As a user I want to be able to create a profile in order to track my weight and measurements
​

## Description

![screenshot-excalidraw com-2023 07 19-16_24_41](https://github.com/oliverhees/capstone/assets/38748506/db64bf27-4fae-4f97-a8a5-d9dc0ce52438)

## Acceptance Criteria

- [ ] Display a form with the following fields:
     - First name (value required)
     - Last name (value required)
     - Weight (value required)
     - BMI (optional)
     - Chest (optional)
     - Abdomen (optional)
     - Hip (optional)
- [ ] if form fields are empty (warning is displayed)
- [ ] save data in a Globalstate (as Array) after click save button
- [ ] after click save button a confirmation is displayed 
that the data has been successfully saved
      ​

## Tasks

- [ ] create a featured branch
- [ ] create a Globalstate
- [ ] create Page called "Profile"
- [ ] create a Footer Icon Navigation
- [ ] create a Header Component
- [ ] insert Header Component to App
- [ ] create Component called "Entry Date"
- [ ] create a Form Component

**Comment by actyvystom** [comment]
A good start 👍🏻 
See some comments:
- Your value proposition does not fit your feature at all, it basically describes the full feature set of your app!
A proposal: 
> As a user I want to be able to create a profile in order to track my weight and measurements 

Then you can adjust your acceptance criteria accordingly and add more detail, e.g. what happens when the user saves the data?

In your scribble, some kind of back button/link is visible. As long as you don't implement navigation features you should not have non-functional buttons or links in your scribbles, otherwise it should be part of your user story.  

We usually don't accept connecting a db as part of the first user story. 
You should think of a simpler pre-step to store the data, e.g. localstorage or even a global state.

**Comment by actyvystom** [comment]
Nice update, getting there 👍🏻 
Anyway some comments regarding your **acceptance criteria**: 
- you should describe your acceptance criteria as if it where test cases and apply more detail, e.g.
- a form with the following input fields should be displayed:
  - a name field with a required input value
  - a surname field with required input value
  - ...
  - a submit button will be displayed
  - clicking the submit button should display a short summary of the saved values
  
Concerning your **task list**:
- There are a few typos (Gobalstate instead of Global state, some missing double quotes) 
- You should remove functionality which won't be working for now, like the Footer Icon navigation component (you should also remove this from the scribble)
- you still have the eventHandler for the DB operations in the list, this should be removed, too

**Comment by actyvystom** [comment]
LGTM 🚀
