### ISSUE TITLE
Create Dashboard

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#3]
## Value Proposition

As a user I would like to have an overview to see all data from profile page
​

## Description

![screenshot-excalidraw com-2023 07 20-10_59_53](https://github.com/oliverhees/capstone/assets/38748506/5b610c87-f97e-4a6f-9b63-41619f31dbfb)

​

## Acceptance Criteria

- [ ] The username and the days that have passed since joining should be displayed.
- [ ] The weight should be displayed in a big box (Globalstate from Profile Page)
- [ ] The data for hips, belly and chest should be displayed (Globalstate from Profile Page)​

## Tasks

- [ ] create a featured branch
- [ ] create a page called "Dashboard"
- [ ] create a component for render weight
- [ ] create a component for render chest, hips and belly

**Comment by AliaksandraNovikava** [comment]
Hey @oliverhees.

I see some logical discrepancy in the order of your USs.
In your first US you create a profile page and in the second you already want to display your achievements. But to do so you first need some kind of updated data and logic that calculates the difference between your initial and updated values, that later should be displayed on your dashboard.

Please consider putting at least one additional US before you work on this one. 
In this US you should cover following topics:
- How do you get updated data (form?)
- Logic to calculate the differences between your initial and new data

(I didn't comment on your acceptance criteria and tasks listed above because they can still change if you add another US in front of this one.)

**Comment by oliverhees** [comment]
Hello @AliaksandraNovikava,

Thank you very much for your detailed comment.

You are right about the logic. The data here is from the profile page and currently there is not the intermediate step to update this data yet.

Since this is an MVP and this step is not necessary yet, I have adjusted everything and will only include advanced logic for this in a later step.

**Comment by vaupunkt** [comment]
Hey 😊
I think the last two points from your acceptance criteria are additional user-storys. 
- [ ] A button to create an automatic training plan shall be displayed
- [ ] After clicking on create training plan a training plan will be created automatically and saved in globalstate

In the current one you only want to see your data, but adding buttons and functionality are userstories of their own 🙏🏻

**Comment by oliverhees** [comment]
Hey @vaupunkt,

thanks for your feedback.

I have edit my US.

**Comment by CorneliusMoe** [comment]
LGTM👍
