### ISSUE TITLE
Create "Trainingsplan"

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#4]
## Value Proposition

As a user I would like to create a training plan

## Description
![screenshot-excalidraw com-2023 07 20-08_44_10](https://github.com/oliverhees/capstone/assets/38748506/0e085889-d6cd-4930-b7f3-d4fbf4c6b980)

## Acceptance Criteria
- [ ] A button to create an automatic training plan shall be displayed
- [ ] After clicking on create training plan a training plan will be created automatically and saved in globalstate

## Tasks

- [ ] create a featured branch
- [ ] create trainingsplan dummydata
- [ ] create a component for button to create a trainingplan from dummy data
- [ ] after create trainingplan it saved at the localstorage

**Comment by CorneliusMoe** [comment]
LGTM👍
