### ISSUE TITLE
Create Page "Mein Trainingsplan"

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#5]
## Value Proposition

As a user I want to be able to click through my training plan to do my exercises

## Description
![screenshot-excalidraw com-2023 07 20-10_25_59](https://github.com/oliverhees/capstone/assets/38748506/ef8f4953-fca1-4497-bc07-63e12a30dd0e)

## Acceptance Criteria
- [ ] The username and the days that have passed since joining should be displayed.
- [ ] The headline "Your training plan" should be displayed
- [ ] A button "back" should be displayed
- [ ] A button "continue" should be displayed
- [ ] after clicking on the button "next" the next exercise is displayed
- [ ] after clicking on the button "back" the previous exercise is displayed

## Tasks

- [ ] create a featured branch
- [ ] create a page called "trainings plan"
- [ ] create a component to render exercises (from Dummydata in Globalstate)
- [ ] create a component for button "weiter"
- [ ] create a component for button "zurück"

**Comment by HannesOster** [comment]
LGTM :)
