### ISSUE TITLE
Create Done Button for Training

### ISSUE THREAD

**Issue by oliverhees** [oliverhees/capstone#9]
## Value Proposition

As a user I want to be able to click through my training plan to do my exercises

## Description
![screenshot-www figma com-2023 08 01-20_07_54](https://github.com/oliverhees/capstone/assets/38748506/31cd974b-a108-44f6-8d2f-bbe85f210387)

## Acceptance Criteria
- [ ] The username and the days that have passed since joining should be displayed.
- [ ] The headline "Your training plan" should be displayed
- [ ] A button "back" should be displayed
- [ ] A button "continue" should be displayed
- [ ] after clicking on the button "next" the next exercise is displayed
- [ ] after clicking on the button "back" the previous exercise is displayed
- [ ] after clicking the "Mark exercise as complete" button it change color and can not click twice
- [ ] after clicking the "Mark exercise as complete" button it save exercise id,date,done on localstorage

## Tasks

- [ ] create a featured branch
- [ ] create a page called "trainings plan"
- [ ] create a component to render exercises (from Dummydata)
- [ ] create a component for button "weiter"
- [ ] create a component for button "zurück"
- [ ] create a component for mark done button
